server:
  port: 8888

spring:
  application:
    name: AMD-Public
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  mvc:
    static-path-pattern=/static/**:
  auth:
    url: http://127.0.0.1:8000/auth
  user:
    url: http://127.0.0.1:8000/user
  dashboard:
    url: http://127.0.0.1:8000/react
  devtools:
    livereload:
      enabled : true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false


eureka:
  instance:
    instacne-id: ${spring.application.name}:${spring.application.instance_id}:${server.port}
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
      enabled: true


logging:
  level:
    com.example.AMD: DEBUG